// Standardized genre list for consistent categorization
export const GENRES = [
  "rock",
  "indie",
  "alternative",
  "pop",
  "hip-hop",
  "r&b",
  "country",
  "folk",
  "metal",
  "punk",
  "electronic",
  "jazz",
  "blues",
  "soul",
  "funk",
  "reggae",
  "classical",
  "latin",
  "world",
  "americana",
  "singer-songwriter",
  "hardcore",
  "emo",
  "ska",
  "psychedelic",
  "experimental",
  "ambient",
  "dance",
  "house",
  "techno",
  "dubstep",
  "drum-and-bass",
  "trap",
  "gospel",
  "christian",
  "comedy",
  "cover-band",
  "tribute",
] as const;

export type Genre = (typeof GENRES)[number];

// For display purposes
export const GENRE_LABELS: Record<Genre, string> = {
  "rock": "Rock",
  "indie": "Indie",
  "alternative": "Alternative",
  "pop": "Pop",
  "hip-hop": "Hip-Hop",
  "r&b": "R&B",
  "country": "Country",
  "folk": "Folk",
  "metal": "Metal",
  "punk": "Punk",
  "electronic": "Electronic",
  "jazz": "Jazz",
  "blues": "Blues",
  "soul": "Soul",
  "funk": "Funk",
  "reggae": "Reggae",
  "classical": "Classical",
  "latin": "Latin",
  "world": "World",
  "americana": "Americana",
  "singer-songwriter": "Singer-Songwriter",
  "hardcore": "Hardcore",
  "emo": "Emo",
  "ska": "Ska",
  "psychedelic": "Psychedelic",
  "experimental": "Experimental",
  "ambient": "Ambient",
  "dance": "Dance",
  "house": "House",
  "techno": "Techno",
  "dubstep": "Dubstep",
  "drum-and-bass": "Drum & Bass",
  "trap": "Trap",
  "gospel": "Gospel",
  "christian": "Christian",
  "comedy": "Comedy",
  "cover-band": "Cover Band",
  "tribute": "Tribute",
};
